  selenium:
    image: selenium/standalone-chrome:3.141
    environment:
      # Required to avoid container startup hanging sometimes
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
    ports:
      - "4444:4444"
